project 'HomeModuleDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HomeModuleDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'TCMBase', :path => '../../TCMBase'
  pod 'HomeModule', :path => '../'
  
  # Pods for HomeModuleDemo

  target 'HomeModuleDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HomeModuleDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
