use_frameworks!

target 'TCMNetworkingKit_Example' do
  pod 'TCMNetworkingKit', :path => '../'

  target 'TCMNetworkingKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
