project 'BaseDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'BaseDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'TCMBase', :path => '../'
  
  # Pods for BaseDemo

  target 'BaseDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
