project 'ComponentDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ComponentDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'TCMComponent', :path => '../'
  
  # Pods for ComponentDemo

  target 'ComponentDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ComponentDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
