project 'LoginModuleDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LoginModuleDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
  
  pod 'TCMBase', :path => '../../TCMBase'
  pod 'LoginModule', :path => '../'
  
  # Pods for LoginModuleDemo

  target 'LoginModuleDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginModuleDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
